package com.blogapp.mapper;

/**
 * Mapper interface between Comment and CommentDto
 * <p>
 * will be generated by Mapstruct
 */

import com.blogapp.entity.Comment;
import com.blogapp.dto.CommentDto;
import org.mapstruct.Mapper;

@Mapper(componentModel = "spring")
public interface CommentMapper extends EntityMapper<CommentDto, Comment> {


}
