package com.blogapp.mapper;

/**
 * Mapper interface between Post and PostDto
 * <p>
 * will be generated by Mapstruct
 */


import com.blogapp.entity.Post;
import com.blogapp.dto.PostDto;
import org.mapstruct.Mapper;

@Mapper(componentModel = "spring")
public interface PostMapper extends EntityMapper<PostDto, Post> {


}

