package com.blogapp.mapper;

/**
 * Mapper interface between User and UserDto
 * <p>
 * will be generated by Mapstruct
 */


import com.blogapp.entity.User;
import com.blogapp.dto.UserDto;
import org.mapstruct.Mapper;

@Mapper(componentModel = "spring")

public interface UserMapper extends EntityMapper<UserDto, User> {


}
